version: 2
jobs:
  build:
    docker:
      - image: cimg/rust:1.61.0
    environment:
      TARGET: x86_64-unknown-linux-gnu
    steps:
      - checkout
      - run:
          name: Version Information
          command: rustc --version; cargo --version; rustup --version; which cargo
      - run:
          name: Check Rust
          command: |
            which cargo; which rustc
            rustc --version
      - run:
          name: Build
          command: ci/script.sh
  tests:
    docker:
      - image: cimg/rust:1.61.0
    environment:
      TARGET: x86_64-unknown-linux-gnu
      CIRCLECI_TEST: "true" # change to false to disable tests
    steps:
      - checkout
      - run:
          name: Run Tests
          command: ci/script.sh

  macos:
    macos:
      xcode: "12.5.1"
    environment:
      RUST_BACKTRACE: 1
      TARGET: x86_64-apple-darwin
      CIRCLECI_TEST: "true" # change to false to disable tests
    steps:
      - checkout
      - run:
          name: Install Rust
          command: |
            sudo mkdir -p /opt
            curl https://sh.rustup.rs -sSf | sh -s -- -y # --default-toolchain << parameters.rust >>
            sudo ln -s ~/.cargo/bin/* /usr/local/bin
      - run:
          name: Rust Version
          command: rustc --version; cargo --version; rustup --version

      - run:
          name: Build
          command: ci/script.sh

workflows:
  version: 2
  build-n-test:
      jobs:
        - build:
            filters:
              branches:
                only: /.*/
        - tests:
            filters:
              branches:
                only: [master, develop]
            requires:
              - build
  build-n-test-mac:
    jobs:
      - macos:
          filters:
            branches:
              only: /.*/
